import type { MetadataRoute } from "next";
import { getSiteUrl } from "@/lib/site-url";

export default function robots(): MetadataRoute.Robots {
  const siteUrl = getSiteUrl();

  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/"],
        disallow: [
          "/admintops",
          "/admintops/",
          "/ai-agent",
          "/ai-agent/",
          "/agents",
          "/agents/",
          "/ai-chatbot",
          "/ai-chatbot/",
          "/admin",
          "/admin/",
          "/article-preview",
          "/article-preview/",
          "/api",
          "/api/",
          "/automations",
          "/automations/",
          "/billing",
          "/billing/",
          "/broadcasts",
          "/broadcasts/",
          "/change-password",
          "/change-password/",
          "/contacts",
          "/contacts/",
          "/dashboard",
          "/dashboard/",
          "/data-deletion/status",
          "/data-deletion/status/",
          "/flows",
          "/flows/",
          "/forgot-password",
          "/forgot-password/",
          "/inbox",
          "/inbox/",
          "/invite",
          "/invite/",
          "/login",
          "/login/",
          "/pending-approval",
          "/pending-approval/",
          "/pipelines",
          "/pipelines/",
          "/settings",
          "/settings/",
          "/signup",
          "/signup/",
          "/team",
          "/team/",
          "/whatsapp-api-pricing",
          "/whatsapp-api-pricing/",
        ],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}
