-- Align hosted Pro broadcast usage with the active billing period.
-- The allowance is one million successfully sent broadcast messages per period.
-- An approved renewal starts a fresh period without deleting historical usage rows.

ALTER TABLE public.workspaces
  ADD COLUMN IF NOT EXISTS broadcast_usage_period_anchor_at TIMESTAMPTZ;

COMMENT ON COLUMN public.workspaces.broadcast_usage_period_anchor_at IS
  'Start timestamp used to calculate the current hosted Pro broadcast allowance period.';

CREATE TABLE IF NOT EXISTS public.workspace_broadcast_usage_resets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  reset_at TIMESTAMPTZ NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  previous_messages_used INTEGER NOT NULL DEFAULT 0 CHECK (previous_messages_used >= 0),
  reason TEXT NOT NULL,
  source_type TEXT,
  source_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (period_end > period_start)
);

CREATE INDEX IF NOT EXISTS idx_workspace_broadcast_usage_resets_workspace
  ON public.workspace_broadcast_usage_resets(workspace_id, reset_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_workspace_broadcast_usage_reset_source
  ON public.workspace_broadcast_usage_resets(workspace_id, source_type, source_id)
  WHERE source_type IS NOT NULL AND source_id IS NOT NULL;

ALTER TABLE public.workspace_broadcast_usage_resets ENABLE ROW LEVEL SECURITY;

REVOKE INSERT, UPDATE, DELETE, TRUNCATE
  ON public.workspace_broadcast_usage_resets
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.workspace_broadcast_usage_resets TO authenticated;

DROP POLICY IF EXISTS "Workspace members can view broadcast usage resets"
  ON public.workspace_broadcast_usage_resets;
CREATE POLICY "Workspace members can view broadcast usage resets"
  ON public.workspace_broadcast_usage_resets
  FOR SELECT
  TO authenticated
  USING (
    public.workspace_has_permission(workspace_id, 'view_broadcasts')
  );

CREATE OR REPLACE FUNCTION public.resolve_workspace_broadcast_period(
  p_anchor_at TIMESTAMPTZ,
  p_at TIMESTAMPTZ DEFAULT NOW()
)
RETURNS TABLE(period_start DATE, period_end DATE)
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $$
DECLARE
  anchor_date DATE := COALESCE(
    (p_anchor_at AT TIME ZONE 'UTC')::DATE,
    (date_trunc('month', p_at AT TIME ZONE 'UTC'))::DATE
  );
  at_date DATE := (p_at AT TIME ZONE 'UTC')::DATE;
  month_offset INTEGER;
  candidate_start DATE;
  candidate_end DATE;
BEGIN
  month_offset := GREATEST(
    (
      EXTRACT(YEAR FROM AGE(at_date, anchor_date))::INTEGER * 12
      + EXTRACT(MONTH FROM AGE(at_date, anchor_date))::INTEGER
    ),
    0
  );

  candidate_start := (anchor_date + make_interval(months => month_offset))::DATE;
  candidate_end := (anchor_date + make_interval(months => month_offset + 1))::DATE;

  WHILE candidate_start > at_date AND month_offset > 0 LOOP
    month_offset := month_offset - 1;
    candidate_start := (anchor_date + make_interval(months => month_offset))::DATE;
    candidate_end := (anchor_date + make_interval(months => month_offset + 1))::DATE;
  END LOOP;

  WHILE candidate_end <= at_date LOOP
    month_offset := month_offset + 1;
    candidate_start := (anchor_date + make_interval(months => month_offset))::DATE;
    candidate_end := (anchor_date + make_interval(months => month_offset + 1))::DATE;
  END LOOP;

  RETURN QUERY SELECT candidate_start, candidate_end;
END;
$$;

CREATE OR REPLACE FUNCTION public.reset_workspace_pro_broadcast_period(
  p_workspace_id UUID,
  p_started_at TIMESTAMPTZ DEFAULT NOW(),
  p_reason TEXT DEFAULT 'subscription_renewed',
  p_source_type TEXT DEFAULT NULL,
  p_source_id TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  workspace_row public.workspaces%ROWTYPE;
  period_start_date DATE;
  period_end_date DATE;
  previous_used INTEGER := 0;
  reset_record_id BIGINT;
BEGIN
  SELECT *
  INTO workspace_row
  FROM public.workspaces
  WHERE id = p_workspace_id
  FOR UPDATE;

  IF NOT FOUND
     OR workspace_row.plan_type <> 'pro'
     OR workspace_row.subscription_status <> 'active' THEN
    RETURN FALSE;
  END IF;

  SELECT bounds.period_start, bounds.period_end
  INTO period_start_date, period_end_date
  FROM public.resolve_workspace_broadcast_period(p_started_at, p_started_at) AS bounds;

  SELECT COALESCE(usage.messages_used, 0)
  INTO previous_used
  FROM public.workspace_broadcast_usage AS usage
  WHERE usage.workspace_id = p_workspace_id
    AND usage.period_start = period_start_date;

  INSERT INTO public.workspace_broadcast_usage_resets (
    workspace_id,
    reset_at,
    period_start,
    period_end,
    previous_messages_used,
    reason,
    source_type,
    source_id
  )
  VALUES (
    p_workspace_id,
    p_started_at,
    period_start_date,
    period_end_date,
    COALESCE(previous_used, 0),
    COALESCE(NULLIF(TRIM(p_reason), ''), 'subscription_renewed'),
    NULLIF(TRIM(p_source_type), ''),
    NULLIF(TRIM(p_source_id), '')
  )
  ON CONFLICT (workspace_id, source_type, source_id)
    WHERE source_type IS NOT NULL AND source_id IS NOT NULL
  DO NOTHING
  RETURNING id INTO reset_record_id;

  IF p_source_type IS NOT NULL
     AND p_source_id IS NOT NULL
     AND reset_record_id IS NULL THEN
    RETURN FALSE;
  END IF;

  UPDATE public.workspaces
  SET
    broadcast_usage_period_anchor_at = p_started_at,
    updated_at = GREATEST(updated_at, p_started_at)
  WHERE id = p_workspace_id;

  INSERT INTO public.workspace_broadcast_usage (
    workspace_id,
    period_start,
    period_end,
    messages_used,
    created_at,
    updated_at
  )
  VALUES (
    p_workspace_id,
    period_start_date,
    period_end_date,
    0,
    p_started_at,
    p_started_at
  )
  ON CONFLICT (workspace_id, period_start) DO UPDATE SET
    period_end = EXCLUDED.period_end,
    messages_used = 0,
    updated_at = EXCLUDED.updated_at;

  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_workspace_broadcast_usage_status(
  p_workspace_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  workspace_row public.workspaces%ROWTYPE;
  pro_limit INTEGER := 1000000;
  period_start_date DATE;
  period_end_date DATE;
  used_count INTEGER := 0;
BEGIN
  SELECT *
  INTO workspace_row
  FROM public.workspaces
  WHERE id = p_workspace_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'used', 0,
      'limit', pro_limit,
      'remaining', pro_limit,
      'reason', 'workspace_not_found'
    );
  END IF;

  SELECT bounds.period_start, bounds.period_end
  INTO period_start_date, period_end_date
  FROM public.resolve_workspace_broadcast_period(
    COALESCE(
      workspace_row.broadcast_usage_period_anchor_at,
      workspace_row.subscription_started_at,
      date_trunc('month', NOW())
    ),
    NOW()
  ) AS bounds;

  SELECT COALESCE(usage.messages_used, 0)
  INTO used_count
  FROM public.workspace_broadcast_usage AS usage
  WHERE usage.workspace_id = p_workspace_id
    AND usage.period_start = period_start_date;

  RETURN jsonb_build_object(
    'used', COALESCE(used_count, 0),
    'limit', pro_limit,
    'remaining', GREATEST(pro_limit - COALESCE(used_count, 0), 0),
    'period_start', period_start_date,
    'period_end', period_end_date
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.reserve_workspace_broadcast_usage(
  p_workspace_id UUID,
  p_message_count INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  workspace_row public.workspaces%ROWTYPE;
  requested INTEGER := GREATEST(COALESCE(p_message_count, 0), 0);
  pro_limit INTEGER := 1000000;
  period_start_date DATE;
  period_end_date DATE;
  usage_row public.workspace_broadcast_usage%ROWTYPE;
  remaining INTEGER;
BEGIN
  IF requested = 0 THEN
    RETURN jsonb_build_object('allowed', true, 'reserved', 0, 'remaining', NULL);
  END IF;

  SELECT *
  INTO workspace_row
  FROM public.workspaces
  WHERE id = p_workspace_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('allowed', false, 'reason', 'workspace_not_found');
  END IF;

  IF workspace_row.plan_type = 'pro'
     AND workspace_row.subscription_status = 'active'
     AND workspace_row.subscription_ends_at IS NOT NULL
     AND workspace_row.subscription_ends_at > NOW() THEN
    SELECT bounds.period_start, bounds.period_end
    INTO period_start_date, period_end_date
    FROM public.resolve_workspace_broadcast_period(
      COALESCE(
        workspace_row.broadcast_usage_period_anchor_at,
        workspace_row.subscription_started_at,
        date_trunc('month', NOW())
      ),
      NOW()
    ) AS bounds;

    INSERT INTO public.workspace_broadcast_usage (
      workspace_id,
      period_start,
      period_end,
      messages_used
    )
    VALUES (
      p_workspace_id,
      period_start_date,
      period_end_date,
      0
    )
    ON CONFLICT (workspace_id, period_start) DO UPDATE SET
      period_end = EXCLUDED.period_end;

    SELECT *
    INTO usage_row
    FROM public.workspace_broadcast_usage
    WHERE workspace_id = p_workspace_id
      AND period_start = period_start_date
    FOR UPDATE;

    remaining := GREATEST(pro_limit - usage_row.messages_used, 0);

    IF requested > remaining THEN
      RETURN jsonb_build_object(
        'allowed', false,
        'reason', 'pro_limit_exceeded',
        'plan_type', workspace_row.plan_type,
        'subscription_status', workspace_row.subscription_status,
        'billing_period', workspace_row.billing_period,
        'subscription_ends_at', workspace_row.subscription_ends_at,
        'used', usage_row.messages_used,
        'limit', pro_limit,
        'remaining', remaining,
        'requested', requested,
        'period_start', usage_row.period_start,
        'period_end', usage_row.period_end
      );
    END IF;

    UPDATE public.workspace_broadcast_usage
    SET
      messages_used = messages_used + requested,
      updated_at = NOW()
    WHERE workspace_id = p_workspace_id
      AND period_start = period_start_date
    RETURNING * INTO usage_row;

    RETURN jsonb_build_object(
      'allowed', true,
      'reserved', requested,
      'plan_type', workspace_row.plan_type,
      'subscription_status', workspace_row.subscription_status,
      'billing_period', workspace_row.billing_period,
      'subscription_ends_at', workspace_row.subscription_ends_at,
      'used', usage_row.messages_used,
      'limit', pro_limit,
      'remaining', GREATEST(pro_limit - usage_row.messages_used, 0),
      'period_start', usage_row.period_start,
      'period_end', usage_row.period_end
    );
  END IF;

  IF workspace_row.plan_type = 'pro' THEN
    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'pro_expired',
      'plan_type', workspace_row.plan_type,
      'subscription_status', workspace_row.subscription_status,
      'billing_period', workspace_row.billing_period,
      'subscription_ends_at', workspace_row.subscription_ends_at,
      'used', 0,
      'limit', pro_limit,
      'remaining', 0
    );
  END IF;

  IF workspace_row.plan_type = 'lifetime'
     OR workspace_row.billing_period = 'lifetime_setup' THEN
    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'lifetime_setup_not_hosted',
      'plan_type', workspace_row.plan_type,
      'subscription_status', workspace_row.subscription_status,
      'billing_period', workspace_row.billing_period,
      'remaining', 0
    );
  END IF;

  RETURN public.reserve_workspace_trial_broadcast_usage(p_workspace_id, requested);
END;
$$;

CREATE OR REPLACE FUNCTION public.release_workspace_broadcast_usage(
  p_workspace_id UUID,
  p_message_count INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  requested INTEGER := GREATEST(COALESCE(p_message_count, 0), 0);
  period_start_date DATE;
  period_end_date DATE;
  workspace_row public.workspaces%ROWTYPE;
BEGIN
  IF requested = 0 THEN
    RETURN;
  END IF;

  SELECT *
  INTO workspace_row
  FROM public.workspaces
  WHERE id = p_workspace_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF workspace_row.plan_type = 'pro' THEN
    SELECT bounds.period_start, bounds.period_end
    INTO period_start_date, period_end_date
    FROM public.resolve_workspace_broadcast_period(
      COALESCE(
        workspace_row.broadcast_usage_period_anchor_at,
        workspace_row.subscription_started_at,
        date_trunc('month', NOW())
      ),
      NOW()
    ) AS bounds;

    UPDATE public.workspace_broadcast_usage
    SET
      messages_used = GREATEST(messages_used - requested, 0),
      updated_at = NOW()
    WHERE workspace_id = p_workspace_id
      AND period_start = period_start_date;
    RETURN;
  END IF;

  PERFORM public.release_workspace_trial_broadcast_usage(p_workspace_id, requested);
END;
$$;

CREATE OR REPLACE FUNCTION public.reset_pro_broadcast_period_after_manual_approval()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.plan_type = 'pro'
     AND NEW.status = 'approved'
     AND OLD.status IS DISTINCT FROM NEW.status
     AND NEW.workspace_id IS NOT NULL THEN
    PERFORM public.reset_workspace_pro_broadcast_period(
      NEW.workspace_id,
      COALESCE(NEW.approved_at, NOW()),
      'manual_payment_approved',
      'manual_payment_request',
      NEW.id::TEXT
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reset_pro_broadcast_period_after_manual_approval
  ON public.manual_payment_requests;
CREATE TRIGGER reset_pro_broadcast_period_after_manual_approval
  AFTER UPDATE OF status ON public.manual_payment_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.reset_pro_broadcast_period_after_manual_approval();

UPDATE public.workspaces AS workspace
SET broadcast_usage_period_anchor_at = COALESCE(
  (
    SELECT MAX(request.approved_at)
    FROM public.manual_payment_requests AS request
    WHERE request.workspace_id = workspace.id
      AND request.plan_type = 'pro'
      AND request.status = 'approved'
      AND request.approved_at >= date_trunc('month', NOW())
  ),
  date_trunc('month', NOW())
)
WHERE workspace.plan_type = 'pro'
  AND workspace.subscription_status = 'active'
  AND workspace.broadcast_usage_period_anchor_at IS NULL;

DO $$
DECLARE
  recent_approval RECORD;
BEGIN
  FOR recent_approval IN
    SELECT DISTINCT ON (request.workspace_id)
      request.id,
      request.workspace_id,
      request.approved_at
    FROM public.manual_payment_requests AS request
    JOIN public.workspaces AS workspace
      ON workspace.id = request.workspace_id
    WHERE request.plan_type = 'pro'
      AND request.status = 'approved'
      AND request.approved_at >= date_trunc('month', NOW())
      AND workspace.plan_type = 'pro'
      AND workspace.subscription_status = 'active'
    ORDER BY request.workspace_id, request.approved_at DESC
  LOOP
    PERFORM public.reset_workspace_pro_broadcast_period(
      recent_approval.workspace_id,
      recent_approval.approved_at,
      'migration_current_period_backfill',
      'manual_payment_request',
      recent_approval.id::TEXT
    );
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.resolve_workspace_broadcast_period(TIMESTAMPTZ, TIMESTAMPTZ)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reset_workspace_pro_broadcast_period(UUID, TIMESTAMPTZ, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_workspace_broadcast_usage_status(UUID)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.resolve_workspace_broadcast_period(TIMESTAMPTZ, TIMESTAMPTZ)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.reset_workspace_pro_broadcast_period(UUID, TIMESTAMPTZ, TEXT, TEXT, TEXT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.get_workspace_broadcast_usage_status(UUID)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.reserve_workspace_broadcast_usage(UUID, INTEGER)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.release_workspace_broadcast_usage(UUID, INTEGER)
  TO authenticated, service_role;
