-- Count only successfully sent/delivered/read/replied broadcast messages
-- against Free Trial and hosted Pro broadcast allowances.
--
-- Context:
-- The worker reserves one usage unit before sending. If Meta accepts the
-- message and later sends a webhook status of `failed`, the recipient row
-- becomes failed after the reservation was already consumed. This migration
-- refunds those historical late-failed recipients once, and records each
-- corrected recipient so the migration is safe to rerun.

CREATE TABLE IF NOT EXISTS public.broadcast_usage_corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  broadcast_id UUID NOT NULL REFERENCES public.broadcasts(id) ON DELETE CASCADE,
  recipient_id UUID NOT NULL REFERENCES public.broadcast_recipients(id) ON DELETE CASCADE,
  correction_type TEXT NOT NULL CHECK (correction_type IN ('late_meta_failed_refund')),
  message_count INTEGER NOT NULL DEFAULT 1 CHECK (message_count > 0),
  corrected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_broadcast_usage_corrections_recipient_type
  ON public.broadcast_usage_corrections(recipient_id, correction_type);

CREATE INDEX IF NOT EXISTS idx_broadcast_usage_corrections_workspace
  ON public.broadcast_usage_corrections(workspace_id, corrected_at DESC);

ALTER TABLE public.broadcast_usage_corrections ENABLE ROW LEVEL SECURITY;

REVOKE INSERT, UPDATE, DELETE, TRUNCATE
  ON public.broadcast_usage_corrections
  FROM PUBLIC, anon, authenticated;

GRANT SELECT ON public.broadcast_usage_corrections TO authenticated;

DROP POLICY IF EXISTS "Workspace members can view broadcast usage corrections"
  ON public.broadcast_usage_corrections;
CREATE POLICY "Workspace members can view broadcast usage corrections"
  ON public.broadcast_usage_corrections
  FOR SELECT
  TO authenticated
  USING (
    public.workspace_has_permission(workspace_id, 'view_broadcasts')
  );

DO $$
BEGIN
  CREATE TEMP TABLE tmp_new_broadcast_usage_corrections (
    workspace_id UUID NOT NULL,
    broadcast_id UUID NOT NULL,
    recipient_id UUID NOT NULL,
    message_count INTEGER NOT NULL
  ) ON COMMIT DROP;

  WITH inserted AS (
    INSERT INTO public.broadcast_usage_corrections (
      workspace_id,
      broadcast_id,
      recipient_id,
      correction_type,
      message_count
    )
    SELECT
      broadcast.workspace_id,
      recipient.broadcast_id,
      recipient.id,
      'late_meta_failed_refund',
      1
    FROM public.broadcast_recipients AS recipient
    JOIN public.broadcasts AS broadcast
      ON broadcast.id = recipient.broadcast_id
    WHERE recipient.status = 'failed'
      AND recipient.whatsapp_message_id IS NOT NULL
      AND recipient.sent_at IS NOT NULL
      AND broadcast.workspace_id IS NOT NULL
    ON CONFLICT (recipient_id, correction_type) DO NOTHING
    RETURNING workspace_id, broadcast_id, recipient_id, message_count
  )
  INSERT INTO tmp_new_broadcast_usage_corrections (
    workspace_id,
    broadcast_id,
    recipient_id,
    message_count
  )
  SELECT
    inserted.workspace_id,
    inserted.broadcast_id,
    inserted.recipient_id,
    inserted.message_count
  FROM inserted;

  WITH pro_adjustments AS (
    SELECT
      corrected.workspace_id,
      usage.period_start,
      SUM(corrected.message_count)::INTEGER AS message_count
    FROM tmp_new_broadcast_usage_corrections AS corrected
    JOIN public.broadcast_recipients AS recipient
      ON recipient.id = corrected.recipient_id
    JOIN public.workspace_broadcast_usage AS usage
      ON usage.workspace_id = corrected.workspace_id
     AND (recipient.sent_at AT TIME ZONE 'UTC')::DATE >= usage.period_start
     AND (recipient.sent_at AT TIME ZONE 'UTC')::DATE < usage.period_end
    JOIN public.workspaces AS workspace
      ON workspace.id = corrected.workspace_id
     AND workspace.plan_type = 'pro'
    GROUP BY corrected.workspace_id, usage.period_start
  )
  UPDATE public.workspace_broadcast_usage AS usage
  SET
    messages_used = GREATEST(usage.messages_used - pro_adjustments.message_count, 0),
    updated_at = NOW()
  FROM pro_adjustments
  WHERE usage.workspace_id = pro_adjustments.workspace_id
    AND usage.period_start = pro_adjustments.period_start;

  WITH trial_adjustments AS (
    SELECT
      corrected.workspace_id,
      SUM(corrected.message_count)::INTEGER AS message_count
    FROM tmp_new_broadcast_usage_corrections AS corrected
    JOIN public.broadcast_recipients AS recipient
      ON recipient.id = corrected.recipient_id
    JOIN public.workspaces AS workspace
      ON workspace.id = corrected.workspace_id
     AND workspace.plan_type = 'trial'
     AND (
       workspace.trial_started_at IS NULL
       OR recipient.sent_at >= workspace.trial_started_at
     )
     AND (
       workspace.trial_ends_at IS NULL
       OR recipient.sent_at <= workspace.trial_ends_at
     )
    GROUP BY corrected.workspace_id
  )
  UPDATE public.workspaces AS workspace
  SET
    trial_broadcast_used = GREATEST(
      COALESCE(workspace.trial_broadcast_used, 0) - trial_adjustments.message_count,
      0
    ),
    updated_at = NOW()
  FROM trial_adjustments
  WHERE workspace.id = trial_adjustments.workspace_id;
END;
$$;
